// react/src/direflow-component/App.tsx
/**
 * Copyright (c) Cisco Systems, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import React, { FC, useContext } from "react";
import { EventContext, Styled } from "direflow-component";
import styles from "./App.css";

interface IProps {
  sampleList: string[];
  componentTitle: string;
}

const App: FC<IProps> = (props) => {
  const dispatch = useContext(EventContext);

  const handleClick = () => {
    const event = new Event("my-event");
    dispatch(event);
  };

  const renderSampleList = props.sampleList.map((sample: string) => (
    <div key={sample} className="sample-text">
      → {sample}
    </div>
  ));

  return (
    <Styled styles={styles}>
      <div className="app">
        <div className="top">
          <div className="header-image" />
        </div>
        <div className="bottom">
          <div className="header-title">{props.componentTitle}</div>
          <div>{renderSampleList}</div>
          <button className="button" onClick={handleClick}>
            Let&apos;s go!
          </button>
        </div>
      </div>
    </Styled>
  );
};

export default App;

// angular/src/app/app.component.ts
/**
 * Copyright (c) Cisco Systems, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { Component } from '@angular/core';
import "@momentum-ui/web-components";
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular';
}

<!-- /** * Copyright (c) Cisco Systems, Inc. and its affiliates. * * This source code
is licensed under the MIT license found in the * LICENSE file in the root
directory of this source tree. * */ -->

<div class="toggle">
  <div class="toggle-container">
    <input
      id="dark-mode-checkbox"
      type="checkbox"
      class="theme-switch"
      data-aspect="darkTheme"
      label="Dark Mode"
    />
    <label for="dark-mode-checkbox">Dark Mode</label>
    <div class="switch-container">
      <label class="switch" text="Responsive"> Widget Boundary </label>
      <input
        type="text"
        id="width-switch"
        class="theme-switch"
        data-aspect="responsive-width"
      />
      <label>x</label>
      <input
        type="text"
        id="height-switch"
        class="theme-switch"
        data-aspect="responsive-height"
      />
    </div>
  </div>
</div>
<div class="container">
  <div style="width: 500px; height: 80vh" class="widget-container">
    <my-custom-component></my-custom-component>
  </div>
</div>
